import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow_2(object):
    def messagebox(self, title, msg):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(msg)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()


    def showalldoc(self):
        con = sqlite3.connect('hms.db')
        self.cur = con.cursor()

        self.cur.execute("SELECT * FROM doc")
        data = self.cur.fetchall()

        if data :
            self.tableWidget.clear()
            self.tableWidget.insertRow(0)
            for row , form in enumerate(data):
                for column , item in enumerate(form):
                    self.tableWidget.setItem(row , column , QtWidgets.QTableWidgetItem(str(item)))
                row_position = self.tableWidget.rowCount()
                self.tableWidget.insertRow(row_position)


    def searchdoc(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        docname = self.lineEdit_Searchd.text()
        self.cur.execute("SELECT * FROM doc WHERE docname=?", (docname,))
        data = self.cur.fetchall()

        if data :
            self.tableWidget.clear()
            self.tableWidget.insertRow(0)
            for row , form in enumerate(data):
                for column , item in enumerate(form):
                    self.tableWidget.setItem(row , column , QtWidgets.QTableWidgetItem(str(item)))
                row_position = self.tableWidget.rowCount()
                self.tableWidget.insertRow(row_position)


    def showallpat(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        self.cur.execute("SELECT * FROM patient")
        data = self.cur.fetchall()

        if data :
            self.tableWidget_2.clear()
            self.tableWidget_2.insertRow(0)
            for row , form in enumerate(data):
                for column , item in enumerate(form):
                    self.tableWidget_2.setItem(row , column , QtWidgets.QTableWidgetItem(str(item)))
                row_position = self.tableWidget_2.rowCount()
                self.tableWidget_2.insertRow(row_position)


    def searchpat(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        fullname = self.lineEdit_pSearch.text()
        self.cur.execute("SELECT * FROM patient WHERE fullname=?" , (fullname,))
        data = self.cur.fetchall()

        if data :
            self.tableWidget_2.clear()
            self.tableWidget_2.insertRow(0)
            for row , form in enumerate(data):
                for column , item in enumerate(form):
                    self.tableWidget_2.setItem(row , column , QtWidgets.QTableWidgetItem(str(item)))
                row_position = self.tableWidget_2.rowCount()
                self.tableWidget_2.insertRow(row_position)


    def addAdmin(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        adminname = self.lineEdit_adn.text()
        adminpw = self.lineEdit_adpw.text()

        self.cur.execute("INSERT INTO admin(adminname,adminpw) VALUES (? , ?)",(adminname,adminpw,))
        self.con.commit()
        self.messagebox("Added", f"{adminname} added sucessfully")

    def removeAdmin(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        adminname = self.lineEdit_adn.text()
        adminpass = self.lineEdit_adpw.text()

        self.cur.execute('''DELETE FROM admin WHERE adminname=? AND adminpw=?''',(adminname,adminpass,))
        self.con.commit()
        self.messagebox("Removed", f"{adminname} removed sucessfully")

    def addDoc(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        docfulln = self.lineEdit_dname_5.text()
        docname = self.lineEdit_dname_5.text()
        docpass = self.lineEdit_dpass.text()
        docspec = self.lineEdit_ds.text()
        docqual = self.lineEdit_dq.text()

        self.cur.execute("INSERT INTO doc(docfullname,docname,docpw,speciality,qualification) VALUES (?, ?, ?, ?, ?)",(docfulln,docname,docpass,docspec,docqual))
        self.con.commit()
        self.messagebox("Added", f"{docname} added sucessfully")

    def removeDoc(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        docname = self.lineEdit_dname_6.text()

        self.cur.execute("DELETE FROM doc WHERE docname=?",(docname,))
        self.con.commit()
        self.messagebox("Removed", f"{docname} removed sucessfully")

    def removePat(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        fullname = self.lineEdit_pname.text()

        self.cur.execute("DELETE FROM patient WHERE fullname=?", (fullname,))
        self.con.commit()
        self.messagebox("Removed", f"{fullname} removed sucessfully")

    def makeBill(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        pname = self.lineEdit_pname_2.text()
        pmeds = self.plainTextEdit.toPlainText()
        temp_date = self.dateEdit.date()
        pdate = temp_date.toString()
        price = float(self.lineEdit_bam.text())

        self.cur.execute("INSERT INTO bill(pname, meds, date, price) VALUES (?, ?, ?, ?)",(pname, pmeds, pdate, price))
        self.con.commit()
        self.messagebox("Bill Generated", f"Bill created and submitted to {pname}")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(250, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        font.setItalic(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_title.setObjectName("label_title")
        self.tabWidget_dname = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_dname.setGeometry(QtCore.QRect(10, 50, 571, 401))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tabWidget_dname.setFont(font)
        self.tabWidget_dname.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_dname.setAutoFillBackground(False)
        self.tabWidget_dname.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_dname.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_dname.setObjectName("tabWidget_dname")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_dname = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_dname.setGeometry(QtCore.QRect(120, 50, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_dname.setFont(font)
        self.lineEdit_dname.setAutoFillBackground(False)
        self.lineEdit_dname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dname.setObjectName("lineEdit_dname")
        self.label_dname = QtWidgets.QLabel(self.tab)
        self.label_dname.setGeometry(QtCore.QRect(30, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dname.setFont(font)
        self.label_dname.setObjectName("label_dname")
        self.label_dname_2 = QtWidgets.QLabel(self.tab)
        self.label_dname_2.setGeometry(QtCore.QRect(260, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dname_2.setFont(font)
        self.label_dname_2.setObjectName("label_dname_2")
        self.lineEdit_dname_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_dname_2.setGeometry(QtCore.QRect(350, 50, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_dname_2.setFont(font)
        self.lineEdit_dname_2.setAutoFillBackground(False)
        self.lineEdit_dname_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dname_2.setObjectName("lineEdit_dname_2")
        self.label_dname_3 = QtWidgets.QLabel(self.tab)
        self.label_dname_3.setGeometry(QtCore.QRect(30, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dname_3.setFont(font)
        self.label_dname_3.setObjectName("label_dname_3")
        self.lineEdit_dname_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_dname_3.setGeometry(QtCore.QRect(120, 90, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_dname_3.setFont(font)
        self.lineEdit_dname_3.setAutoFillBackground(False)
        self.lineEdit_dname_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dname_3.setObjectName("lineEdit_dname_3")
        self.lineEdit_dname_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_dname_4.setGeometry(QtCore.QRect(350, 90, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_dname_4.setFont(font)
        self.lineEdit_dname_4.setAutoFillBackground(False)
        self.lineEdit_dname_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dname_4.setObjectName("lineEdit_dname_4")
        self.label_dname_4 = QtWidgets.QLabel(self.tab)
        self.label_dname_4.setGeometry(QtCore.QRect(260, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dname_4.setFont(font)
        self.label_dname_4.setObjectName("label_dname_4")
        self.tabWidget_dname_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_dname_2.setGeometry(QtCore.QRect(0, -30, 571, 401))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tabWidget_dname_2.setFont(font)
        self.tabWidget_dname_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_dname_2.setStyleSheet("border-color: rgb(54, 54, 54);")
        self.tabWidget_dname_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_dname_2.setObjectName("tabWidget_dname_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_dname_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_dname_5.setGeometry(QtCore.QRect(120, 80, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_dname_5.setFont(font)
        self.lineEdit_dname_5.setAutoFillBackground(False)
        self.lineEdit_dname_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dname_5.setObjectName("lineEdit_dname_5")
        self.label_dname_5 = QtWidgets.QLabel(self.tab_3)
        self.label_dname_5.setGeometry(QtCore.QRect(30, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dname_5.setFont(font)
        self.label_dname_5.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_dname_5.setObjectName("label_dname_5")
        self.label_dpass = QtWidgets.QLabel(self.tab_3)
        self.label_dpass.setGeometry(QtCore.QRect(300, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dpass.setFont(font)
        self.label_dpass.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_dpass.setObjectName("label_dpass")
        self.lineEdit_dpass = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_dpass.setGeometry(QtCore.QRect(390, 80, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_dpass.setFont(font)
        self.lineEdit_dpass.setAutoFillBackground(False)
        self.lineEdit_dpass.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_dpass.setObjectName("lineEdit_dpass")
        self.label_ds = QtWidgets.QLabel(self.tab_3)
        self.label_ds.setGeometry(QtCore.QRect(30, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_ds.setFont(font)
        self.label_ds.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_ds.setObjectName("label_ds")
        self.lineEdit_ds = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_ds.setGeometry(QtCore.QRect(120, 120, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_ds.setFont(font)
        self.lineEdit_ds.setAutoFillBackground(False)
        self.lineEdit_ds.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_ds.setObjectName("lineEdit_ds")
        self.lineEdit_dq = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_dq.setGeometry(QtCore.QRect(390, 120, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_dq.setFont(font)
        self.lineEdit_dq.setAutoFillBackground(False)
        self.lineEdit_dq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dq.setObjectName("lineEdit_dq")
        self.label_dq = QtWidgets.QLabel(self.tab_3)
        self.label_dq.setGeometry(QtCore.QRect(300, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dq.setFont(font)
        self.label_dq.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_dq.setObjectName("label_dq")
        self.pushButton_dadd = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_dadd.setGeometry(QtCore.QRect(240, 170, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_dadd.setFont(font)
        self.pushButton_dadd.setAutoFillBackground(False)
        self.pushButton_dadd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_dadd.setObjectName("pushButton_dadd")
        self.pushButton_dadd.clicked.connect(self.addDoc)
        self.lineEdit_dname_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_dname_6.setGeometry(QtCore.QRect(160, 290, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_dname_6.setFont(font)
        self.lineEdit_dname_6.setAutoFillBackground(False)
        self.lineEdit_dname_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dname_6.setObjectName("lineEdit_dname_6")
        self.label_dname_6 = QtWidgets.QLabel(self.tab_3)
        self.label_dname_6.setGeometry(QtCore.QRect(70, 290, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dname_6.setFont(font)
        self.label_dname_6.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_dname_6.setObjectName("label_dname_6")
        self.label_title_2 = QtWidgets.QLabel(self.tab_3)
        self.label_title_2.setGeometry(QtCore.QRect(200, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_title_2.setFont(font)
        self.label_title_2.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_title_2.setObjectName("label_title_2")
        self.pushButton_drm = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_drm.setGeometry(QtCore.QRect(320, 290, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_drm.setFont(font)
        self.pushButton_drm.setAutoFillBackground(False)
        self.pushButton_drm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_drm.setObjectName("pushButton_drm")
        self.pushButton_drm.clicked.connect(self.removeDoc)
        self.label_title_3 = QtWidgets.QLabel(self.tab_3)
        self.label_title_3.setGeometry(QtCore.QRect(220, 230, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_title_3.setFont(font)
        self.label_title_3.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_title_3.setObjectName("label_title_3")
        self.tabWidget_dname_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_dname_2.addTab(self.tab_4, "")
        self.tabWidget_dname.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_pname = QtWidgets.QLabel(self.tab_2)
        self.label_pname.setGeometry(QtCore.QRect(90, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_pname.setFont(font)
        self.label_pname.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_pname.setObjectName("label_pname")
        self.pushButton_prm = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_prm.setGeometry(QtCore.QRect(340, 60, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_prm.setFont(font)
        self.pushButton_prm.setAutoFillBackground(False)
        self.pushButton_prm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_prm.setObjectName("pushButton_prm")
        self.pushButton_prm.clicked.connect(self.removePat)
        self.lineEdit_pname = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_pname.setGeometry(QtCore.QRect(180, 60, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_pname.setFont(font)
        self.lineEdit_pname.setAutoFillBackground(False)
        self.lineEdit_pname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_pname.setObjectName("lineEdit_pname")
        self.label_dname_18 = QtWidgets.QLabel(self.tab_2)
        self.label_dname_18.setGeometry(QtCore.QRect(190, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_dname_18.setFont(font)
        self.label_dname_18.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_dname_18.setObjectName("label_dname_18")
        self.label_dname_21 = QtWidgets.QLabel(self.tab_2)
        self.label_dname_21.setGeometry(QtCore.QRect(240, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_dname_21.setFont(font)
        self.label_dname_21.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_dname_21.setObjectName("label_dname_21")
        self.lineEdit_pname_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_pname_2.setGeometry(QtCore.QRect(120, 160, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_pname_2.setFont(font)
        self.lineEdit_pname_2.setAutoFillBackground(False)
        self.lineEdit_pname_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_pname_2.setObjectName("lineEdit_pname_2")
        self.label_pname_2 = QtWidgets.QLabel(self.tab_2)
        self.label_pname_2.setGeometry(QtCore.QRect(20, 160, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_pname_2.setFont(font)
        self.label_pname_2.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_pname_2.setObjectName("label_pname_2")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit.setGeometry(QtCore.QRect(400, 160, 110, 22))
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setAutoFillBackground(True)
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit.setObjectName("dateEdit")
        self.label_bdate = QtWidgets.QLabel(self.tab_2)
        self.label_bdate.setGeometry(QtCore.QRect(260, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_bdate.setFont(font)
        self.label_bdate.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_bdate.setObjectName("label_bdate")
        self.label_med = QtWidgets.QLabel(self.tab_2)
        self.label_med.setGeometry(QtCore.QRect(20, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_med.setFont(font)
        self.label_med.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_med.setObjectName("label_med")
        self.lineEdit_bam = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_bam.setGeometry(QtCore.QRect(120, 290, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_bam.setFont(font)
        self.lineEdit_bam.setAutoFillBackground(False)
        self.lineEdit_bam.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_bam.setObjectName("lineEdit_bam")
        self.label_bam = QtWidgets.QLabel(self.tab_2)
        self.label_bam.setGeometry(QtCore.QRect(20, 290, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_bam.setFont(font)
        self.label_bam.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_bam.setObjectName("label_bam")
        self.pushButton_mb = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_mb.setGeometry(QtCore.QRect(230, 330, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_mb.setFont(font)
        self.pushButton_mb.setAutoFillBackground(False)
        self.pushButton_mb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_mb.setObjectName("pushButton_mb")
        self.pushButton_mb.clicked.connect(self.makeBill)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(113, 200, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setAutoFillBackground(True)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget_dname.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_dname_13 = QtWidgets.QLabel(self.tab_5)
        self.label_dname_13.setGeometry(QtCore.QRect(210, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_dname_13.setFont(font)
        self.label_dname_13.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_dname_13.setObjectName("label_dname_13")
        self.lineEdit_Searchd = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_Searchd.setGeometry(QtCore.QRect(300, 20, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_Searchd.setFont(font)
        self.lineEdit_Searchd.setAutoFillBackground(False)
        self.lineEdit_Searchd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Searchd.setObjectName("lineEdit_Searchd")
        self.pushButton_Search = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_Search.setGeometry(QtCore.QRect(430, 20, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_Search.setFont(font)
        self.pushButton_Search.setAutoFillBackground(False)
        self.pushButton_Search.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.pushButton_Search.clicked.connect(self.searchdoc)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 551, 301))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.pushButton_Showall = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_Showall.setGeometry(QtCore.QRect(40, 20, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_Showall.setFont(font)
        self.pushButton_Showall.setAutoFillBackground(False)
        self.pushButton_Showall.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_Showall.setObjectName("pushButton_Showall")
        self.pushButton_Showall.clicked.connect(self.showalldoc)
        self.tabWidget_dname.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.lineEdit_pSearch = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_pSearch.setGeometry(QtCore.QRect(290, 20, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_pSearch.setFont(font)
        self.lineEdit_pSearch.setAutoFillBackground(False)
        self.lineEdit_pSearch.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_pSearch.setObjectName("lineEdit_pSearch")
        self.pushButton_pSearch = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_pSearch.setGeometry(QtCore.QRect(420, 20, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_pSearch.setFont(font)
        self.pushButton_pSearch.setAutoFillBackground(False)
        self.pushButton_pSearch.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_pSearch.setObjectName("pushButton_pSearch")
        self.pushButton_pSearch.clicked.connect(self.searchpat)
        self.label_pname_5 = QtWidgets.QLabel(self.tab_6)
        self.label_pname_5.setGeometry(QtCore.QRect(200, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_pname_5.setFont(font)
        self.label_pname_5.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_pname_5.setObjectName("label_pname_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 60, 541, 301))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.pushButton_pShowall = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_pShowall.setGeometry(QtCore.QRect(30, 20, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_pShowall.setFont(font)
        self.pushButton_pShowall.setAutoFillBackground(False)
        self.pushButton_pShowall.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_pShowall.setObjectName("pushButton_pShowall")
        self.pushButton_pShowall.clicked.connect(self.showallpat)
        self.tabWidget_dname.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.lineEdit_adn = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_adn.setGeometry(QtCore.QRect(270, 70, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_adn.setFont(font)
        self.lineEdit_adn.setAutoFillBackground(False)
        self.lineEdit_adn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_adn.setObjectName("lineEdit_adn")
        self.pushButton_adadd = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_adadd.setGeometry(QtCore.QRect(160, 180, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_adadd.setFont(font)
        self.pushButton_adadd.setAutoFillBackground(False)
        self.pushButton_adadd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_adadd.setObjectName("pushButton_adadd")
        self.pushButton_adadd.clicked.connect(self.addAdmin)
        self.label_adn = QtWidgets.QLabel(self.tab_7)
        self.label_adn.setGeometry(QtCore.QRect(170, 70, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_adn.setFont(font)
        self.label_adn.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_adn.setObjectName("label_adn")
        self.lineEdit_adpw = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_adpw.setGeometry(QtCore.QRect(270, 120, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_adpw.setFont(font)
        self.lineEdit_adpw.setAutoFillBackground(False)
        self.lineEdit_adpw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_adpw.setObjectName("lineEdit_adpw")
        self.label_adpw = QtWidgets.QLabel(self.tab_7)
        self.label_adpw.setGeometry(QtCore.QRect(170, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_adpw.setFont(font)
        self.label_adpw.setStyleSheet("color: rgb(255, 11, 104);")
        self.label_adpw.setObjectName("label_adpw")
        self.pushButton_adrm = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_adrm.setGeometry(QtCore.QRect(290, 180, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_adrm.setFont(font)
        self.pushButton_adrm.setAutoFillBackground(False)
        self.pushButton_adrm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_adrm.setObjectName("pushButton_adrm")
        self.pushButton_adrm.clicked.connect(self.removeAdmin)
        self.tabWidget_dname.addTab(self.tab_7, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_dname.setCurrentIndex(4)
        self.tabWidget_dname_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Admin "))
        self.label_title.setText(_translate("MainWindow", "Admin"))
        self.label_dname.setText(_translate("MainWindow", "Doctor Name :"))
        self.label_dname_2.setText(_translate("MainWindow", "Doctor Name :"))
        self.label_dname_3.setText(_translate("MainWindow", "Doctor Name :"))
        self.label_dname_4.setText(_translate("MainWindow", "Doctor Name :"))
        self.label_dname_5.setText(_translate("MainWindow", "Doctor Name :"))
        self.label_dpass.setText(_translate("MainWindow", "Password :"))
        self.label_ds.setText(_translate("MainWindow", "Specialization :"))
        self.label_dq.setText(_translate("MainWindow", "Qualification :"))
        self.pushButton_dadd.setText(_translate("MainWindow", "Add"))
        self.label_dname_6.setText(_translate("MainWindow", "Doctor Name :"))
        self.label_title_2.setText(_translate("MainWindow", "Add a new Doctor"))
        self.pushButton_drm.setText(_translate("MainWindow", "Remove"))
        self.label_title_3.setText(_translate("MainWindow", "Remove Doctor"))
        self.tabWidget_dname_2.setTabText(self.tabWidget_dname_2.indexOf(self.tab_3), _translate("MainWindow", "Manage Doctors"))
        self.tabWidget_dname_2.setTabText(self.tabWidget_dname_2.indexOf(self.tab_4), _translate("MainWindow", "Manage Patients"))
        self.tabWidget_dname.setTabText(self.tabWidget_dname.indexOf(self.tab), _translate("MainWindow", "Manage Doctors"))
        self.label_pname.setText(_translate("MainWindow", "Patient Name :"))
        self.pushButton_prm.setText(_translate("MainWindow", "Remove"))
        self.label_dname_18.setText(_translate("MainWindow", "Remove Patient"))
        self.label_dname_21.setText(_translate("MainWindow", "Bill"))
        self.label_pname_2.setText(_translate("MainWindow", "Patient Name :"))
        self.label_bdate.setText(_translate("MainWindow", "Date (mm/dd/yyyy) :"))
        self.label_med.setText(_translate("MainWindow", "Medications :"))
        self.label_bam.setText(_translate("MainWindow", "Total Amount :"))
        self.pushButton_mb.setText(_translate("MainWindow", "Make Bill"))
        self.tabWidget_dname.setTabText(self.tabWidget_dname.indexOf(self.tab_2), _translate("MainWindow", "Manage Patients"))
        self.label_dname_13.setText(_translate("MainWindow", "Doctor Name :"))
        self.pushButton_Search.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "iddoc"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "docfulln"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "docname"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "docpw"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "speciality"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "qualification"))
        self.pushButton_Showall.setText(_translate("MainWindow", "Show All"))
        self.tabWidget_dname.setTabText(self.tabWidget_dname.indexOf(self.tab_5), _translate("MainWindow", "All Doctors"))
        self.pushButton_pSearch.setText(_translate("MainWindow", "Search"))
        self.label_pname_5.setText(_translate("MainWindow", "Patient Name :"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "pid"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "fullname"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "pusername"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ppassword"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "age"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "gender"))
        self.pushButton_pShowall.setText(_translate("MainWindow", "Show All"))
        self.tabWidget_dname.setTabText(self.tabWidget_dname.indexOf(self.tab_6), _translate("MainWindow", "All Patients"))
        self.pushButton_adadd.setText(_translate("MainWindow", "Add"))
        self.label_adn.setText(_translate("MainWindow", "Admin Name :"))
        self.label_adpw.setText(_translate("MainWindow", "Password :"))
        self.pushButton_adrm.setText(_translate("MainWindow", "Remove"))
        self.tabWidget_dname.setTabText(self.tabWidget_dname.indexOf(self.tab_7), _translate("MainWindow", "New Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
