import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from Admin import Ui_MainWindow_2
from Doctor import Ui_MainWindow_3
from Patient import Ui_MainWindow_4

class Ui_MainWindow_5(object):

    # Message Box
    def messagebox(self, title, msg):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(msg)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    # Open Admin Window
    def openWindowAdmin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_2()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    # Open Doctor Window
    def openWindowDoctor(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_3()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    # Open Patient Window
    def openWindowPatient(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_4()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    # Login System
    def loginAdmin(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()
        username = self.lineEdit_AdminU.text()
        password = self.lineEdit_AdminP.text()
        query = "SELECT * FROM admin WHERE adminname=? and adminpw=?"
        data = self.cur.execute(query, (username, password))
        if (len(self.cur.fetchall()) > 0):
            self.messagebox("Congrats", "Login Sucessful")
            self.openWindowAdmin()
        else:
            self.messagebox("Error", "Enter correct details")
        self.con.close()

    def loginDoctor(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        username = self.lineEdit_DocU.text()
        password = self.lineEdit_DocP.text()
        query = "SELECT * FROM doc WHERE docname=? and docpw=?"
        data = self.cur.execute(query, (username, password))
        if (len(self.cur.fetchall()) > 0):
            self.messagebox("Congrats", "Login Sucessful")
            self.openWindowDoctor()
        else:
            self.messagebox("Error", "Enter correct details")

    def loginPatient(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        username = self.lineEdit_PatU.text()
        password = self.lineEdit_PatP.text()
        query = "SELECT * FROM patient WHERE pusername=? and ppassword=?"
        data = self.cur.execute(query, (username, password))
        if (len(self.cur.fetchall()) > 0):
            self.messagebox("Congrats", "Login Sucessful")
            self.openWindowPatient()
        else:
            self.messagebox("Error", "Enter correct details")

    # Add Patient
    def addPatient(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        fname = self.lineEdit_PatFN.text()
        uname = self.lineEdit_PatU_2.text()
        ppw = self.lineEdit_PatP_3.text()
        page = self.spinBox.value()
        pgender = str(self.comboBox.currentText())
        self.cur.execute('''INSERT INTO patient(fullname,pusername,ppassword,age,gender) VALUES (?,?,?,?,?)''',(fname,uname,ppw,page,pgender,))
        # self.db.commit()
        self.con.commit()
        self.messagebox("Added","Patient added sucessfully")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(170, 30, 271, 91))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(36)
        font.setItalic(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_title.setObjectName("label_title")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 160, 571, 301))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"border-color: rgb(170, 170, 255);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_AdminP = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_AdminP.setGeometry(QtCore.QRect(250, 110, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_AdminP.setFont(font)
        self.lineEdit_AdminP.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_AdminP.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_AdminP.setObjectName("lineEdit_AdminP")
        self.lineEdit_AdminU = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_AdminU.setGeometry(QtCore.QRect(250, 70, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_AdminU.setFont(font)
        self.lineEdit_AdminU.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_AdminU.setObjectName("lineEdit_AdminU")
        self.label_AdminP = QtWidgets.QLabel(self.tab)
        self.label_AdminP.setGeometry(QtCore.QRect(160, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_AdminP.setFont(font)
        self.label_AdminP.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_AdminP.setObjectName("label_AdminP")
        self.pushButton_AdminSubmit = QtWidgets.QPushButton(self.tab)
        self.pushButton_AdminSubmit.setGeometry(QtCore.QRect(240, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_AdminSubmit.setFont(font)
        self.pushButton_AdminSubmit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_AdminSubmit.setObjectName("pushButton_AdminSubmit")
        self.pushButton_AdminSubmit.clicked.connect(self.loginAdmin)
        self.label_AdminN = QtWidgets.QLabel(self.tab)
        self.label_AdminN.setGeometry(QtCore.QRect(160, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_AdminN.setFont(font)
        self.label_AdminN.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_AdminN.setObjectName("label_AdminN")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_DocU = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_DocU.setGeometry(QtCore.QRect(250, 70, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_DocU.setFont(font)
        self.lineEdit_DocU.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_DocU.setObjectName("lineEdit_DocU")
        self.label_DocU = QtWidgets.QLabel(self.tab_2)
        self.label_DocU.setGeometry(QtCore.QRect(160, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_DocU.setFont(font)
        self.label_DocU.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_DocU.setObjectName("label_DocU")
        self.pushButton_DocSubmit = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_DocSubmit.setGeometry(QtCore.QRect(240, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_DocSubmit.setFont(font)
        self.pushButton_DocSubmit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_DocSubmit.setObjectName("pushButton_DocSubmit")
        self.pushButton_DocSubmit.clicked.connect(self.loginDoctor)
        self.label_DocP = QtWidgets.QLabel(self.tab_2)
        self.label_DocP.setGeometry(QtCore.QRect(160, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_DocP.setFont(font)
        self.label_DocP.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_DocP.setObjectName("label_DocP")
        self.lineEdit_DocP = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_DocP.setGeometry(QtCore.QRect(250, 110, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_DocP.setFont(font)
        self.lineEdit_DocP.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_DocP.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_DocP.setObjectName("lineEdit_DocP")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_PatU = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_PatU.setGeometry(QtCore.QRect(250, 70, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_PatU.setFont(font)
        self.lineEdit_PatU.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_PatU.setObjectName("lineEdit_PatU")
        self.label_PatU = QtWidgets.QLabel(self.tab_3)
        self.label_PatU.setGeometry(QtCore.QRect(160, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_PatU.setFont(font)
        self.label_PatU.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_PatU.setObjectName("label_PatU")
        self.pushButton_PatSubmit = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_PatSubmit.setGeometry(QtCore.QRect(240, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_PatSubmit.setFont(font)
        self.pushButton_PatSubmit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_PatSubmit.setObjectName("pushButton_PatSubmit")
        self.pushButton_PatSubmit.clicked.connect(self.loginPatient)
        self.label_PatP = QtWidgets.QLabel(self.tab_3)
        self.label_PatP.setGeometry(QtCore.QRect(160, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_PatP.setFont(font)
        self.label_PatP.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_PatP.setObjectName("label_PatP")
        self.lineEdit_PatP = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_PatP.setGeometry(QtCore.QRect(250, 110, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_PatP.setFont(font)
        self.lineEdit_PatP.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_PatP.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_PatP.setObjectName("lineEdit_PatP")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_PatU_2 = QtWidgets.QLabel(self.tab_4)
        self.label_PatU_2.setGeometry(QtCore.QRect(50, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_PatU_2.setFont(font)
        self.label_PatU_2.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_PatU_2.setObjectName("label_PatU_2")
        self.lineEdit_PatFN = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_PatFN.setGeometry(QtCore.QRect(160, 40, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_PatFN.setFont(font)
        self.lineEdit_PatFN.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_PatFN.setObjectName("lineEdit_PatFN")
        self.lineEdit_PatU_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_PatU_2.setGeometry(QtCore.QRect(140, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_PatU_2.setFont(font)
        self.lineEdit_PatU_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_PatU_2.setObjectName("lineEdit_PatU_2")
        self.label_PatFN = QtWidgets.QLabel(self.tab_4)
        self.label_PatFN.setGeometry(QtCore.QRect(50, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_PatFN.setFont(font)
        self.label_PatFN.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_PatFN.setObjectName("label_PatFN")
        self.pushButton_PatSubmit_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_PatSubmit_2.setGeometry(QtCore.QRect(220, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_PatSubmit_2.setFont(font)
        self.pushButton_PatSubmit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_PatSubmit_2.setObjectName("pushButton_PatSubmit_2")
        self.pushButton_PatSubmit_2.clicked.connect(self.addPatient)
        self.label_PatP_3 = QtWidgets.QLabel(self.tab_4)
        self.label_PatP_3.setGeometry(QtCore.QRect(310, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_PatP_3.setFont(font)
        self.label_PatP_3.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_PatP_3.setObjectName("label_PatP_3")
        self.lineEdit_PatP_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_PatP_3.setGeometry(QtCore.QRect(390, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_PatP_3.setFont(font)
        self.lineEdit_PatP_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_PatP_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_PatP_3.setObjectName("lineEdit_PatP_3")
        self.label_PatP_4 = QtWidgets.QLabel(self.tab_4)
        self.label_PatP_4.setGeometry(QtCore.QRect(50, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_PatP_4.setFont(font)
        self.label_PatP_4.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_PatP_4.setObjectName("label_PatP_4")
        self.spinBox = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox.setGeometry(QtCore.QRect(130, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.spinBox.setFont(font)
        self.spinBox.setAutoFillBackground(True)
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox.setObjectName("spinBox")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(380, 120, 69, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_PatP_5 = QtWidgets.QLabel(self.tab_4)
        self.label_PatP_5.setGeometry(QtCore.QRect(310, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_PatP_5.setFont(font)
        self.label_PatP_5.setStyleSheet("color: rgb(200, 14, 79);")
        self.label_PatP_5.setObjectName("label_PatP_5")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "My Healthcare Login"))
        self.label_title.setText(_translate("MainWindow", "My HeathCare"))
        self.label_AdminP.setText(_translate("MainWindow", "Password :"))
        self.pushButton_AdminSubmit.setText(_translate("MainWindow", "Submit"))
        self.label_AdminN.setText(_translate("MainWindow", "Username :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Admin Login"))
        self.label_DocU.setText(_translate("MainWindow", "Username :"))
        self.pushButton_DocSubmit.setText(_translate("MainWindow", "Submit"))
        self.label_DocP.setText(_translate("MainWindow", "Password :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Doctor Login"))
        self.label_PatU.setText(_translate("MainWindow", "Username :"))
        self.pushButton_PatSubmit.setText(_translate("MainWindow", "Submit"))
        self.label_PatP.setText(_translate("MainWindow", "Password :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Patient Login"))
        self.label_PatU_2.setText(_translate("MainWindow", "Username :"))
        self.label_PatFN.setText(_translate("MainWindow", "Patient Name :"))
        self.pushButton_PatSubmit_2.setText(_translate("MainWindow", "Submit"))
        self.label_PatP_3.setText(_translate("MainWindow", "Password :"))
        self.label_PatP_4.setText(_translate("MainWindow", "Age :"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Male"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Female"))
        self.label_PatP_5.setText(_translate("MainWindow", "Gender :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "New Patient"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_5()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())