import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow_4(object):
    def messagebox(self, title, msg):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(msg)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()


    def makeapt(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        pname = self.lineEdit_pname.text()
        docname = self.lineEdit_dname.text()
        temp_date = self.dateEdit.date()
        aptdate = temp_date.toString()

        self.cur.execute("INSERT INTO appointment(pname,docname,date) VALUES (?, ?, ?)",(pname,docname,aptdate))
        self.con.commit()
        self.messagebox("Done", "Appointment Fixed")


    def showapt(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        pname = self.lineEdit.text()
        self.cur.execute("SELECT * FROM appointment WHERE pname=? ORDER BY date ASC",(pname,))
        data = self.cur.fetchall()

        if data:
            self.tableWidget.clear()
            self.tableWidget.insertRow(0)
            for row, form in enumerate(data):
                for column, item in enumerate(form):
                    self.tableWidget.setItem(row, column, QtWidgets.QTableWidgetItem(str(item)))
                row_position = self.tableWidget.rowCount()
                self.tableWidget.insertRow(row_position)


    def showbills(self):
        self.con = sqlite3.connect("hms.db")
        self.cur = self.con.cursor()

        pname = self.lineEdit.text()
        self.cur.execute("SELECT * FROM bill WHERE pname=? ORDER BY date ASC",(pname,))
        data = self.cur.fetchall()

        if data:
            self.tableWidget_2.clear()
            self.tableWidget_2.insertRow(0)
            for row, form in enumerate(data):
                for column, item in enumerate(form):
                    self.tableWidget_2.setItem(row, column, QtWidgets.QTableWidgetItem(str(item)))
                row_position = self.tableWidget_2.rowCount()
                self.tableWidget_2.insertRow(row_position)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(190, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        font.setItalic(True)
        self.label_title.setFont(font)
        self.label_title.setAutoFillBackground(False)
        self.label_title.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_title.setObjectName("label_title")
        self.lineEdit_pname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pname.setGeometry(QtCore.QRect(170, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.lineEdit_pname.setFont(font)
        self.lineEdit_pname.setAutoFillBackground(False)
        self.lineEdit_pname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_pname.setObjectName("lineEdit_pname")
        self.label_pname = QtWidgets.QLabel(self.centralwidget)
        self.label_pname.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_pname.setFont(font)
        self.label_pname.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_pname.setObjectName("label_pname")
        self.lineEdit_dname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dname.setGeometry(QtCore.QRect(430, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.lineEdit_dname.setFont(font)
        self.lineEdit_dname.setAutoFillBackground(False)
        self.lineEdit_dname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_dname.setObjectName("lineEdit_dname")
        self.label_pname_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_pname_2.setGeometry(QtCore.QRect(320, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_pname_2.setFont(font)
        self.label_pname_2.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_pname_2.setObjectName("label_pname_2")
        self.label_pname_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_pname_3.setGeometry(QtCore.QRect(190, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_pname_3.setFont(font)
        self.label_pname_3.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_pname_3.setObjectName("label_pname_3")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(320, 110, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setAutoFillBackground(True)
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 150, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.makeapt)
        self.label_title_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_title_2.setGeometry(QtCore.QRect(50, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        font.setItalic(True)
        self.label_title_2.setFont(font)
        self.label_title_2.setAutoFillBackground(False)
        self.label_title_2.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_title_2.setObjectName("label_title_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 200, 601, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(6, 259, 591, 191))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 561, 151))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setGeometry(QtCore.QRect(5, 10, 571, 151))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setAutoFillBackground(True)
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_4, "")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.showapt)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.showbills)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 230, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Patient"))
        self.label_title.setText(_translate("MainWindow", "Make Appointment"))
        self.label_pname.setText(_translate("MainWindow", "Patient Name :"))
        self.label_pname_2.setText(_translate("MainWindow", "Doctor Name :"))
        self.label_pname_3.setText(_translate("MainWindow", "Appointment Date :"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.pushButton.setText(_translate("MainWindow", "Make Appointment"))
        self.label_title_2.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "apid"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "pname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "docname"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "My Appointments"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "bid"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "pname"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "meds"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "date"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "My Bills"))
        self.pushButton_2.setText(_translate("MainWindow", "Show Appointments"))
        self.pushButton_3.setText(_translate("MainWindow", "Show Bills"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter your name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_4()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
